name: sf-engineering
run-name: ${{ github.actor }} is learning GitHub Actions

# Event: main branch가 업데이트 될때 Actions 작동
on:
  pull_request:
    branches:
      - main

jobs:
  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    step:
      # chekcout action의 3 버전을 Actions으로써 실행
      - name: Checkout Code
        uses: actions/checkout@v3

      # Dockerhub 로그인
      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      # Docker build
      - name: Build Docker Image
        run: |
          docker buildx build --platform linux/amd64 -t ${{ secrets.DOCKER_USERNAME }}/fastapi_app:latest .

      # Docker push
      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/fastapi_app:latest

  deploy:
    name: Deploy on AWS EC2
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      # chekcout action의 3 버전을 Actions으로써 실행
      - name: Checkout Code
        uses: actions/checkout@v3

      # AWS EC2 연결 및 배포
      - name: Connect to AWS EC2 and Deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ${{ secrets.AWS_USER }}
          key: ${{ secrets.AWS_PRIVATE_KEY }}
          port: 22 
          # 기존 AWS EC2 서버에서 수행한 명령어 작성
          script: |
            cd sf
            sudo docker stop fastapi
            sudo docker rm fastapi
            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/fastapi_app:latest
            sudo docker run -d -p 8000:8000 --name fastapi --env-file .env ${{ secrets.DOCKER_USERNAME }}/fastapi_app:latest
